### ISSUE TITLE
search is slow

### ISSUE THREAD

**Issue by goneri** [redhat-cip/dci-ui#19]
If I search the 'ironic' pattern, the result takes about 1 minute. Once the page is finally displayed, I've again to wait =~ 1 minute, to get the it fully operational (_A lot_ of background requests are still ongoing)

**Comment by goneri** [comment]
I use this URL: https://www.distributed-ci.io/#/logs?pattern=tripleo-stack-dump%20lab2%20has%20failed%20with

**Comment by guillaumevincent** [comment]
Close this one, search page doesn't exists anymore
