### ISSUE TITLE
Jobs>Files should be a patternfly list

### ISSUE THREAD

**Issue by Spredzy** [redhat-cip/dci-ui#23]
Most list in the UI has been migrated to the patternfly list.

The one in Jobs>Files is still the old way. In order to keep same UX across all the interface, this list should also be moved to the patternfly list.

**Comment by guillaumevincent** [comment]
![screen shot 2017-05-24 at 09 56 37](https://cloud.githubusercontent.com/assets/943762/26392685/c128bea8-4067-11e7-84a6-4aa2ba6c113d.png)
