### ISSUE TITLE
Long text in errors moves the notification box close button off-screen.

### ISSUE THREAD

**Issue by fcharlier** [redhat-cip/dci-ui#30]
Example, create a team with a very very long name (which currently fails)

![2017-06-12-162058_641x359_scrot](https://user-images.githubusercontent.com/165673/27038436-4b838754-4f8b-11e7-886c-f7ffbd42f0cd.png)

**Comment by guillaumevincent** [comment]
This is more a patternfly issue 
Will create a upstream patch
