### ISSUE TITLE
Download link from Topics > Components is broken

### ISSUE THREAD

**Issue by Spredzy** [redhat-cip/dci-ui#35]
In the Topics > Components > (unfold component) page a 'Download' link is present. But when clicking on it nothing happens. Hence there is no way to download the link from the UI.

**Comment by guillaumevincent** [comment]
What is the purpose of the Download button?
What is the expected behavior?

**Comment by Spredzy** [comment]
@guillaumevincent As mentioned in IRC, the expected behavior is to dowload the associated component.
