### ISSUE TITLE
Ability to delete jobs

### ISSUE THREAD

**Issue by gaelrehault** [redhat-cip/dci-ui#42]
We've lost the ability to delete jobs ,would be nice to have this back to clean up results.

**Comment by guillaumevincent** [comment]
Hello,
the associated review https://softwarefactory-project.io/r/#/c/10022/
will be in production soon

**Comment by guillaumevincent** [comment]
![675e2b46-31cb-4408-a75c-570df5894e4b](https://user-images.githubusercontent.com/943762/32092003-fd44db9c-baf6-11e7-99e0-57149c054622.png)
