### ISSUE TITLE
remotecis from teams on a 2nd level of deph are hidden

### ISSUE THREAD

**Issue by goneri** [redhat-cip/dci-ui#49]
I'm PO in the OpenStack team, I can see the remotecis in the new "Remotecis" menu on the right. They are all here with the exception of the Pure one. What makes this remoteci special is that Pure is itself a sub-team of RAX.

**Comment by guillaumevincent** [comment]
Hi Goneri,
maybe it's a dci-control-server issue because I'm not sure if I'm filtering the remotecis I get.

**Comment by goneri** [comment]
@guillaumevincent , yes indeed. I don't have the problem anymore if I switch to the admin account.

    curl -u admin:fooo 'https://api.distributed-ci.io/api/v1/remotecis'|jq -r .remotecis[].name

**Comment by guillaumevincent** [comment]
So I close this one
Thanks
