### ISSUE TITLE
UI forces the user to reconnect every 20 minutes

### ISSUE THREAD

**Issue by goneri** [redhat-cip/dci-ui#50]
Hi,

During my daily activity, I've 3 or 4 tabs running www.distributed-ci.io. I tend to open a new one, do some stuff and forget about it. When I jump back to a older one, most of the time, I've reauth myself through the SSO. The 1h session has expired.

**Comment by goneri** [comment]
The session expires way faster than what I said in my previous post. It's more like 20 minutes.

**Comment by guillaumevincent** [comment]
Closed by https://softwarefactory-project.io/r/#/c/11149/
