### ISSUE TITLE
the UI does not show up the remoteci list just after a SSO auth

### ISSUE THREAD

**Issue by goneri** [redhat-cip/dci-ui#51]
1. log out
2. log in using SSO

There is no remoteci list

3. refresh

The remoteci list appears.

**Comment by goneri** [comment]
I just reproduce the issue with the admin account (no SSO).

**Comment by guillaumevincent** [comment]
I can't reproduce the issue, can you check again @goneri?

**Comment by goneri** [comment]
Well, it looks better now. I just tried on FF and Chrome.
