### ISSUE TITLE
Cannot update my email if connect through SSO

### ISSUE THREAD

**Issue by goneri** [redhat-cip/dci-ui#53]
I'm using my SSO account. I try to update my email address in my settings. When I click on "Update your settings" nothing happens and there is no error message.

**Comment by guillaumevincent** [comment]
There is no password when connected with the SSO. So we can't change the email.

**Comment by goneri** [comment]
So in this case we should disable the form for the SSO users.

**Comment by guillaumevincent** [comment]
@goneri I think again this is a backend issue.

`PUT` on `https://api.distributed-ci.io/api/v1/users/me` should allow settings update without password if the user is a SSO user.

**Comment by guillaumevincent** [comment]
It will be fix by https://softwarefactory-project.io/r/#/c/11390/

**Comment by guillaumevincent** [comment]
I close, there is a card for this one and it's related to the control server.
