### ISSUE TITLE
Show the full date in addition to human readable indication

### ISSUE THREAD

**Issue by fcharlier** [redhat-cip/dci-ui#62]
In the job list only a human indication of the date a job was run is showed:
- "5 hours ago"
- "two days ago"
- "one month ago"

Specially older jobs like "one month ago", I'd like to be able to know the full date for the job, my initial expectation was that I'd be able to see it when hovering with the mouse cursor but it doesn't show.

**Comment by guillaumevincent** [comment]
If you see a tooltip with the full timestamp is enough for you?

**Comment by fcharlier** [comment]
This would be enough, yes.
