### ISSUE TITLE
no way to delete job anymore

### ISSUE THREAD

**Issue by goneri** [redhat-cip/dci-ui#63]
Since the transition to the new UI, we cannot delete jobs anymore.

**Comment by guillaumevincent** [comment]
I thought that during the grooming it was said that we removed the ability to delete a job and change its status via the ui.
IIRC we decided to add debug tag/meta in the agent by default, and hide by default jobs with tag/meta debug.

**Comment by goneri** [comment]
As said today during the stand-up. I don't remember such discussion, BTW I don't really care if the job is actually deleted. We just need a way to permanently ignore a job.

**Comment by goneri** [comment]
Thanks @guillaumevincent :heart:
