### ISSUE TITLE
ability to jump to the last job

### ISSUE THREAD

**Issue by goneri** [redhat-cip/dci-ui#65]
I often have an old job open and I want to jump to the last job. This force me to do several click before I can finally browse the freshly created job. I would love to have a little link somewhere to this page.

**Comment by guillaumevincent** [comment]
Hello,
if you are on the job details page you need one click to access the latest job. 
if you are on the job list summaries in a different page you also need one click.

Let do a quick bluejeans to help me understand your scenario.

**Comment by guillaumevincent** [comment]
I added the card on the trello board
Close this one
