### ISSUE TITLE
Filter by team is ineffective 

### ISSUE THREAD

**Issue by goneri** [redhat-cip/dci-ui#67]
Hi!

![multi-goneri](https://user-images.githubusercontent.com/49379/45972053-ae385980-c008-11e8-8f33-454411aeba1b.png)

The results are not sorted when I select a team. In the example above, i was expecting to only see the jobs from my team, but this may be a misunderstanding.

Cheers

**Comment by guillaumevincent** [comment]
@goneri this first Team select is here to pre filter the remotecis we display in the second select.
But let me check if we can add the filter by team_id and remoteci_id together.
If so I will add a pre team_id selection when we select the team.

**Comment by goneri** [comment]
:heart:
