### ISSUE TITLE
team list menu is not refreshed is the cache is experired

### ISSUE THREAD

**Issue by goneri** [redhat-cip/dci-ui#68]
(Very minor issue IMO)

1. Go in the job list, and filter on a given team
2. Go in the team list and edit a team
3. Go back in the job list and try to filter on a team
    - the menu is empty
    - Ctrl^r fix the problem

![screenshot from 2018-10-01 11-00-38](https://user-images.githubusercontent.com/49379/46296834-42ef0a00-c569-11e8-8cb2-d7e8f7c2429c.png)

**Comment by guillaumevincent** [comment]
Hello Goneri,
I can't reproduce this issue.
And it will probably be fixed after https://github.com/redhat-cip/dci-ui/issues/71 fix
I close

**Comment by guillaumevincent** [comment]
fix for #71 https://softwarefactory-project.io/r/#/c/13876/
