### ISSUE TITLE
`delete job` action is silently ignored

### ISSUE THREAD

**Issue by goneri** [redhat-cip/dci-ui#73]
I'm super admin and I cannot delete any job with the `delete job` menu.

**Comment by guillaumevincent** [comment]
I tested today, and I can't reproduce
Probably a permission issue.
Can you tell me which user/role your are using?

**Comment by goneri** [comment]
Nope. It's not better :-(

**Comment by guillaumevincent** [comment]
@goneri can you answer my question?

**Comment by goneri** [comment]
My account, it indeed works fine with admin.
