### ISSUE TITLE
Can we have a link to docs from home page of DCI?

### ISSUE THREAD

**Issue by pkchavva** [redhat-cip/dci-ui#75]
The home page of DCI https://www.distributed-ci.io/j is not linked to http://doc.distributed-ci.io

http://doc.distributed-ci.io has a lot of great content and it is a good starting point for Partners or anyone trying to understand DCI,but there is no easy way partners can visit the doc page without having to remember it.

It would be useful to have a link on the homepage and within the dashboard to the docs page.

**Comment by guillaumevincent** [comment]
Hi @pkchavva,
yes the documentation link will be on the login page of the future version of DCI
See https://softwarefactory-project.io/r/#/c/14021/9/src/login/LoginContainer.js
The update will be on production next week.

**Comment by guillaumevincent** [comment]
The documentation link is on the login page of distributed-ci
I close
