### ISSUE TITLE
Can we show/see the time a specific job was run by a partner?

### ISSUE THREAD

**Issue by pkchavva** [redhat-cip/dci-ui#78]
When I am reviewing the jobs run by a partner I can see the complete list of jobs run.

However,I am unable to understand when (time) a specific job was run by the partner.

In this example I checked with Goneri,but I want to understand more about when a Partner had a green run the last time or when the job was run.

The workaround is to go to Global Status which gives the last partners which ran DCI on a particular build with the time.

![screenshot-www distributed-ci io-2018 11 13-10-34-50](https://user-images.githubusercontent.com/25849453/48424136-feda5200-e72f-11e8-966c-5eabc15f9a36.png)

**Comment by guillaumevincent** [comment]
Yes dimitri raise this issue also
It will be fixed tomorrow. Sorry for this missing feature during the migration

**Comment by pkchavva** [comment]
Thank you very much,Appreciate your help!
