### ISSUE TITLE
The file tab is hidden

### ISSUE THREAD

**Issue by goneri** [redhat-cip/dci-ui#81]
Hi,

The "Files" tab is no available anymore. I've to modify the URL to access the page.

**Comment by guillaumevincent** [comment]
![screenshot_2018-11-20 distributed ci](https://user-images.githubusercontent.com/943762/48763997-c518c680-ecae-11e8-8053-54f927255339.png)

I have the file tab, I don't understand your issue

**Comment by goneri** [comment]
Oh! This is super confusing :-(

**Comment by guillaumevincent** [comment]
Fixes by https://softwarefactory-project.io/r/14660 Move the job detail menu in Page section
