### ISSUE TITLE
"See details" link is not functional

### ISSUE THREAD

**Issue by goneri** [redhat-cip/dci-ui#82]
The "See details" button from the job does not do anything.

![image](https://user-images.githubusercontent.com/49379/48734083-630a8380-ec12-11e8-915d-344badfc2c7d.png)

**Comment by guillaumevincent** [comment]
See details is a link to see the detail of a job
Are you already on the detail job page?

**Comment by goneri** [comment]
Yes I am, I was expecting more information. Like the job tab :-) https://github.com/redhat-cip/dci-ui/issues/81

**Comment by guillaumevincent** [comment]
I can hide the see details button when you are in the detail page if you want

**Comment by guillaumevincent** [comment]
Fixed by https://softwarefactory-project.io/r/14653 Hide see details button when we are already in see details page
