### ISSUE TITLE
Time Zone change not allowed for user.

### ISSUE THREAD

**Issue by shajuvk** [redhat-cip/dci-ui#83]
While updating the time zone, UI gives an error 'current_password_invalid'. 
https://www.distributed-ci.io/profile

To Recreate issue.

1. select a different time zone under profile tab 
2. click on Update your settings. 

Note: I am using Redhat sso loin

**Comment by guillaumevincent** [comment]
This is related to your SSO account.
I created the bug in the appropriate project : https://github.com/redhat-cip/dci-control-server/issues/73

Thank you for your bug report
