### ISSUE TITLE
Failed test result value not showing when sufficiently large

### ISSUE THREAD

**Issue by sjabasti** [redhat-cip/dci-ui#87]
When the value of failed test cases is large, they are not shown in the UI. Some quick look at chrome network shows the value is received.

The first screenshot shows the problem
![Screenshot from 2019-10-10 17-19-47](https://user-images.githubusercontent.com/9497139/66583381-8409f900-eb83-11e9-8696-1d12a6a91948.png)

The second screenshot is to demonstrate there should be actual error log (it is taken from the test result html file)
![Screenshot from 2019-10-10 17-18-51](https://user-images.githubusercontent.com/9497139/66583468-ae5bb680-eb83-11e9-8fd7-73bb93e80bc0.png)

**Comment by guillaumevincent** [comment]
could you send me by email gvincent(at)redhat.com the job id?
I will take a look
Thank you

**Comment by sjabasti** [comment]
sent
